version: "3"

services:

  mail_server:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    container_name: db
